### ISSUE TITLE
Folder location and template

### ISSUE THREAD

**Issue by Saorsa32** [Erallie/diarian#1]
How can we set it up so that each new entry is automatically added to a particular folder? Also, will we be able to add a template?

**Comment by Erallie** [comment]
Hello!

For folders, see [here](https://github.com/Erallie/diarian?tab=readme-ov-file#multiplenested-daily-notes). If you still need further help on it, let me know. :)

Also, yes on the templates. I just haven't gotten around to incorporating that feature yet. It's lower on the priority list since you can also insert a template just like you would any other template from the ribbon menu. But yes, I *do* plan on adding a feature to choose a template when you create a new daily note, and the plan is for it to default to the template you defined under **Settings → Daily notes**

**Comment by Erallie** [comment]
@Saorsa32 I just pushed a new update with the requested feature. Let me know if anything is broken :)

**Comment by ElsaTam** [comment]
@Erallie It is working, but there are still your debug notices when the app finds daily note templates from the Daily note core plugin (no notice when it finds ones from the Template core plugin).
Also, once you set a template from the Daily note core plugin, you can't chose "none" anymore. I don't no if it's intended or not, so I thought I would share anyways :)

**Comment by Erallie** [comment]
> It is working, but there are still your debug notices when the app finds daily note templates from the Daily note core plugin (no notice when it finds ones from the Template core plugin).

@ElsaTam When do the debug notices happen, and what do they say?

> Also, once you set a template from the Daily note core plugin, you can't chose "none" anymore. I don't no if it's intended or not, so I thought I would share anyways :)

Omg yeah I forgot to add that back. Thank you! I will add that!

**Comment by ElsaTam** [comment]
@Erallie Woops sorry. Notices happen when clicking on "create a new daily note", on the opening of the modal. Probably because you fetch what is available to fill the select dropdown. And they just give the name of the file. Twice. "Daily Template.md" x2

**Comment by Erallie** [comment]
@ElsaTam okay thanks I think I found it!

I think I fixed the issues. I will change the `styles.css` to fix some more things I found, and then I'll push a new release ^^

**Comment by Erallie** [comment]
@ElsaTam I pushed an update. Can you just check to verify that everything is fixed and still working correctly?

**Comment by ElsaTam** [comment]
@ElsaTam It's all good now. Thanks!

**Comment by Erallie** [comment]
> @ElsaTam It's all good now. Thanks!

@ElsaTam No, thank *you!*

I will close this issue now. @Saorsa32 If you still need help with the folder location or the templates feature isn't working, just comment on the issue again (or re-open it if that's available to you). :)
