### ISSUE TITLE
[Feature request] Calendar - Banner image support

### ISSUE THREAD

**Issue by javiavid** [Erallie/diarian#3]
# Is your feature request related to a problem? Please describe.
I would like the calendar image to be compatible with the banner plugin, which is widely used.

# Describe the solution you'd like
I think there could be an option to search in the properties of the note if an image exists and then in the content.

The banner syntax is as follows:
banner: "[[image.jpg]]"

# Additional context
https://github.com/noatpad/obsidian-banners
In the releases section there are more updated versions.

**Comment by Erallie** [comment]
Hi! I think that's a _great_ idea! I will look into implementing that!

**Comment by Erallie** [comment]
So @javiavid I just tested it out... and it looks like the way it's already coded, using the banner with the plugin already shows up on the calendar tile for that day...

![image](https://github.com/user-attachments/assets/7e02d8bf-42fd-47f0-bfe3-d2fca539c2c3)

This is how it looks like in my vault... does it not show up for you?

**Comment by Erallie** [comment]
Wait. I think I figured it out. If you're using a wikilink to an image in your vault, it works fine, but if it's an image to the web or something, it doesn't. I will fix that. I will need to look into any other methods of inserting an image into the banner property, and try to add that as well, but for now I'll just add wikilinks and weblinks.

If someone is reading this who knows whether there are more, please comment!

**Comment by javiavid** [comment]
Thank you

**Comment by Erallie** [comment]
@javiavid I pushed a new release with support for it! Thank you so much for making this request!! Can you test it out for me and make sure that everything works?

**Comment by Erallie** [comment]
@etamisie Can you also test it out for me?

**Comment by javiavid** [comment]
Thanks for the release. I just checked and I get an icon instead of the images.

![image](https://github.com/user-attachments/assets/6b1fe341-d891-481c-9327-c5deaa3e51d0)

**Comment by Erallie** [comment]
@javiavid Did you update the plugin? And what is the exact value the property is set to?

**Comment by javiavid** [comment]
Yes, I updated the plugin (1.1.37)

![image](https://github.com/user-attachments/assets/ad7e05cf-43b3-492b-8005-39814f8086e9)

**Comment by Erallie** [comment]
@javiavid When I input that syntax into the banner property, the plugin says it's the incorrect syntax, so I didn't add support for *that*, I added support for the syntax I got to work. Does that actually work with the plugin? If it does, I will add support for it.

**Comment by javiavid** [comment]
Thanks for checking it

For banners to work well they need to be without ! 
At least on my obsidian. Banners is ok for you with ! ?

![image](https://github.com/user-attachments/assets/76251e5b-ff9f-468c-9e4e-eebed6cb25e3)

![image](https://github.com/user-attachments/assets/83786f29-5f89-4936-83d8-ea00a8d704a4)

**Comment by Erallie** [comment]
@javiavid That's so weird... what version of Banners are you using? I just downloaded it yesterday and I was on version 1.3.3

For me, it *only* works with the exclamation mark ( ! ) in front, and *doesn't* work without it.

**Comment by javiavid** [comment]
😄I think it's because they changed the syntax in version 2.

Would it be very complicated to be compatible with both forms?

https://github.com/noatpad/obsidian-banners/issues/150

**Comment by Erallie** [comment]
@javiavid I went ahead and added support for that syntax. Please let me know if it works now!

**Comment by javiavid** [comment]
It works! Thanks a lot

**Comment by Erallie** [comment]
@javiavid Wonderful! I'm glad it works! Thank you for using my plugin too!! Please reach out again if you need anything else! I will close this issue now ^^

**Comment by websurfer93** [comment]
> @javiavid That's so weird... what version of Banners are you using? I just downloaded it yesterday and I was on version 1.3.3
> 
> For me, it _only_ works with the exclamation mark ( ! ) in front, and _doesn't_ work without it.

I also find that it only works with the exclamation mark in front. However, I need to utilize it without the exclamation mark due to my use of the metadata menu for media. Is there a way to adjust this?

**Comment by Erallie** [comment]
@websurfer93 What version of Diarian are you using? It should work now regardless of whether there is an exclamation mark in front, as long as you are using the property you set in the plugin.

**Comment by Erallie** [comment]
> @websurfer93 What version of Diarian are you using? It should work now regardless of whether there is an exclamation mark in front, as long as you are using the property you set in the plugin.

@websurfer93 I reopened this issue so we could troubleshoot your thing. 🙂

**Comment by websurfer93** [comment]
> What version of Diarian are you using? It should work now regardless of whether there is an exclamation mark in front, as long as you are using the property you set in the plugin.

Mb, my bad - I actually had a question about the banner plugin, not the Diarian one. Turns out the ! is required for it to render properly. Just wanted to check if there's a way to get it to work without the !.

**Comment by Erallie** [comment]
@websurfer93 javiavid was using an older version of the banner plugin. They said it got changed in version 2 🙂

**Comment by javiavid** [comment]
Hello, I am sending you a screenshot to try to help.

Top - with !
Down - without !

![image](https://github.com/user-attachments/assets/612908ac-23b9-4e0a-9b1c-08165f2069d2)

**Comment by Erallie** [comment]
I am closing this issue since no one has commented on it in a while, and the remaining problems are not related to Diarian ^^
