### ISSUE TITLE
[Feature request] Support differents type daily notes format

### ISSUE THREAD

**Issue by khanhtoan529** [Erallie/diarian#70]
Before all my notes are formated in YYYY-MM-DD

Now I change daily notes format to YYYY-MM-DD HH.mm.ss to using multiple daily notes feature. But after that, all my daily notes before is not regconize anymore (e.g On this day feature)

Propose solution: Support get all daily notes format that following moment.js format

**Comment by Erallie** [comment]
@khanhtoan529 IU apologize for not getting to this until now; I was busy getting ready for a performance I have in VR. I actually make the plugin get the daily notes format from your Daily notes settings, but since your old daily notes don't follow the new format, they aren't recognized by the plugin anymore. I *could* perhaps have an option to change the names of previous daily notes with a push of a button. Would that be a good fix for you?

**Comment by khanhtoan529** [comment]
You're referring to a bulk rename, correct? I think it might be challenging if users decide to discontinue the plugin; in that scenario, they would have to manually revert their notes to the original naming format.

**Comment by Erallie** [comment]
@khanhtoan529 No, I'm not talking about Bulk Rename; I'm saying I can add my own functionality to my own plugin Diarian to rename the notes according to their ctime.

**Comment by khanhtoan529** [comment]
That would be great! I hope it can be implemented. 🥰🙏

**Comment by Erallie** [comment]
@khanhtoan529 Okay then! Yeah I'll add that to my to-do list! I most likely won't be able to get to it until after I deal with a few other things outside of Obsidian, though.

**Comment by Erallie** [comment]
@khanhtoan529 I just pushed a new release with a new date format converter. Can you maybe test this out for me and let me know if it fixes your issue?

**Comment by ElsaTam** [comment]
Hey! I tried it on Windows.
- Changed the format in the Daily Note core plugin
- Convert from the old name to the new name with this new feature from Diarian
- Everything worked, no crash to report :)

**Comment by Erallie** [comment]
@ElsaTam Wonderful! Thank you! I will close this issue now.

@khanhtoan529 If you need anything else related to this feature, just comment on the issue again, and I will reopen it!

**Comment by khanhtoan529** [comment]
@Erallie Hi Erallie,
I tried but it stopped after coverted few notes. I checked the console and it show like this:
![image](https://github.com/user-attachments/assets/4e226d1d-ad82-4d42-850a-d1473e9d9c5d)

**Comment by Erallie** [comment]
@khanhtoan529 Oh sorry I didn't see this comment until after the other issue was already open! I will merge the two issues.
