### ISSUE TITLE
[Feature request] Remove images from calendar view

### ISSUE THREAD

**Issue by t-if** [Erallie/diarian#72]
# Describe the solution you'd like
Option to remove images from calendar view.

# Describe alternatives you've considered
I tried the Daily Note Outline plugin, but I don't like the layout.

# Additional context
I use a banner snippet. This leads to all my days having the same picture, and the banner takes up a lot of space in the note preview. I'd like to be able to remove it, so I can focus on the note contents, and the calendar won't hurt my eyes (banner is a gif).

![image](https://github.com/user-attachments/assets/e86f420a-bbae-431e-8bf8-3d0199e3642c)

Thanks you so much!

**Comment by Erallie** [comment]
@t-if I'm thinking of ways I can implement this. Maybe I can have an option in the settings to exclude banner images from the Calendar view and the note previews? And then it will only exclude things that match the regex for banners?

**Comment by t-if** [comment]
It doesn't matter much for me how you do it lol. I don't really embed things into my daily notes - I just use them to keep track of things

**Comment by Erallie** [comment]
@t-if I just pushed a new release with settings to disable the banner images in the Calendar tiles and note previews. Please let me know if it works for you so I can close this issue!

**Comment by t-if** [comment]
> @t-if I just pushed a new release with settings to disable the banner images in the Calendar tiles and note previews. Please let me know if it works for you so I can close this issue!

Yes, it works. Thank you so much! 
![image](https://github.com/user-attachments/assets/3dbad21a-d9dc-42dd-baca-5bdfb96e290e)

**Comment by Erallie** [comment]
@t-if Yeah ofc! Glad it helped! I will close this issue now 🙂
