### ISSUE TITLE
[Bug] - Daily Notes not created in Calendar not considered in the Calendar

### ISSUE THREAD

**Issue by Minus10Celcius** [Erallie/diarian#74]
# Describe the bug
I create daily notes not in Diarian but with the core plugin, but the Diarian Calendar wont consider the daily note and the only way to show it on the calendar is by creating it in the calendar.
# To Reproduce
1. Just don't create the note in the calendar
2. See results by checking calendar
# Expected behavior
I wanted the daily notes to be seen in the calendar instead of being blank.

# Screenshots
![image](https://github.com/user-attachments/assets/bc5b2dfe-e56e-4415-ab0c-d06ee7b38659)
![image](https://github.com/user-attachments/assets/01162a85-2f9c-4feb-b97b-72f8b14e3157)

# Specs
 - Platform: [Linux]
 - Plugin version: [1.2.8]

# Additional context

Even the Diarian ribbon I sometimes create notes doesn't show with the calendar.

**Comment by Erallie** [comment]
@Minus10Celcius Hi. When I create a new daily note from just the normal core plugin, it still shows up in the Calendar view for me. I'm unable to reproduce the bug. How are you creating a new daily note? Are you using the command from the core plugin, or are you just creating a new note and renaming it to match your daily note format? And if it's the latter, does it show up in the calendar after you refresh the calendar?

**Comment by Minus10Celcius** [comment]
I create daily notes from the core plugin!

**Comment by Erallie** [comment]
@Minus10Celcius What are your settings for the Daily notes **Date format** and **New file location**? It shows up fine for me after using the command from the Daily notes core plugin... I can't seem to replicate the issue.

**Comment by Minus10Celcius** [comment]
OOPS, rookie mistake... I needed to set my daily note folder to the actual folder instead of the subfolder of the daily note folder :P
