### ISSUE TITLE
[Bug] Import fails when not exporting tags

### ISSUE THREAD

**Issue by lludriga** [Erallie/diarian#76]
# Describe the bug
If the json is exported from diarium without tags, the importer fails without feedback.

# To Reproduce
1. Export the json from Diarium, and uncheck the tags.
2. Try to import it to the obsidian vault using the importer.

# Expected behavior
It should work, just not including any tags. Or maybe at least say why it failed and how to make it work.

# Screenshots
It just remains on Starting import..., and if you open the console it says:
![20241011_23h03m31s_grim](https://github.com/user-attachments/assets/4c385270-e279-4657-a05b-68ef6d3c119b)

# Specs
 - Platform: Linux
 - Plugin version: 1.2.10

# Additional context
The error is in this part of the code:

```typescript
function formatContent(array, moment10, mapViewProperty, plugin) {
  let frontmatter = "---";
  if (array.location) {
    frontmatter += `
${mapViewProperty}: ${array.location}`;
  }
  if (array.rating) {
    frontmatter += `
${plugin.settings.ratingProp}: ${array.rating}/5`;
  }
  if (array.tags.length != 0) {
    frontmatter += `
tags:`;
    for (let i in array.tags) {
      frontmatter += `
  - ${array.tags[i]}`;
    }
  }
```

I don't know enough programming to fix it, but I suppose it tries to check a property that doesn't exist.

**Comment by Erallie** [comment]
@lludriga I just pushed a new release. Let me know if it fixes things for you!

**Comment by lludriga** [comment]
Yes, it works perfectly fine now. Thank you a lot for this plugin! And sorry for the delay.

**Comment by Erallie** [comment]
@lludriga Great! I shall close this issue now!
